### ISSUE TITLE
How to make it bigger

### ISSUE THREAD

**Issue by hejinqiao** [erikflowers/weather-icons#129]
Hi, I have been looking for the code to scale the icon, but I only saw wi-fw, which does not work for me. Would you mind showing me how to make my icon bigger?

**Comment by d2s** [comment]
@hejinqiao
Adjust the `font-size` to your preferred icon size, as seen in the following example (from the source code of [documentation](https://erikflowers.github.io/weather-icons/) site).
```css
.icon-wrap .icon,
.icon-wrap .wi {
    font-size: 40px;
}
```

_Extra tip:_
Use tools like [Chrome Developer Tools](https://developer.chrome.com/devtools) to [inspect individual page elements](https://developer.chrome.com/devtools/docs/dom-and-styles) to find out how CSS styles work. Live editing of [styles](https://developer.chrome.com/devtools/docs/dom-and-styles#styles) is also possible, so you can experiment with actual sites to understand better how they are built.

**Comment by erik-intuit** [comment]
Size is controlled by CSS font-size. There aren't any built in controls for sizing as everyone needs it differently. FW is just so that the icons are all the same width in the container, it doesn't change the size. 

There are countless ways to target how you want the icons sized, so I can't really recommend a best way other than to choose where you want to apply font-size most logically.

**Comment by erikflowers** [comment]
Size is controlled by CSS font-size. There aren't any built in controls for sizing as everyone needs it differently. FW is just so that the icons are all the same width in the container, it doesn't change the size. 

There are countless ways to target how you want the icons sized, so I can't really recommend a best way other than to choose where you want to apply font-size most logically.

**Comment by hejinqiao** [comment]
@d2s Thank you, it works! And thank you for your kind advice!

**Comment by hejinqiao** [comment]
@erikflowers Understood. Thank you!
