### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by devloe** [erikflowers/weather-icons#166]
Do you have source for each icon (in SVG; AI, or whatever) available for download?

**Comment by erikflowers** [comment]
The art all exists in the .otf or .glyphs file, they aren’t all separated
out into actual files. You can get a trial of “Glyphs Mini” app and open it
and paste the vectors into Illustrator or something similar.



On July 4, 2016 at 9:47:00 AM, Juan Pablo Lozano (notifications@github.com)
wrote:

Do you have source for each icon (in SVG; AI, or whatever) available for
download?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/erikflowers/weather-icons/issues/166>, or mute the
thread
<https://github.com/notifications/unsubscribe/AA3u277fFBm2uzVurqN33dC6IVmEfITaks5qSTkDgaJpZM4JEg-0>
.

**Comment by devloe** [comment]
I need the icons for an iOS app. I added the font as a custom font, but dont know how to make it work in a uilabel.

**Comment by devloe** [comment]
Nevermind. I made a script to save icons to png. You just only have to specify an xml, which can be the xml used for android.
