### ISSUE TITLE
How to use wind direction icons?

### ISSUE THREAD

**Issue by taerran** [erikflowers/weather-icons#167]
I'm working with android-studio.

Where is CSS directory? and how to include CSS file in my project?

**Comment by erikflowers** [comment]
I am not sure I can answer this, I do not know anything about android
development.



On July 15, 2016 at 12:23:50 AM, Mun Taejin (notifications@github.com)
wrote:

I'm working with android-studio.
in my code,
======.xml===============
android:id="@+id/three_days_widget_winddirection1"
style="@style/THREE_DAYS_ITEM_WINDDIRECTION"/>

======MainActivity========
WeatherIconView view =
(WeatherIconView)mView.findViewById(R.id.three_days_widget_winddirection1);
view.setIconResource(R.string.wi_from_n);

But, R.string.wi_from_n has compile error.

Where is CSS directory? and how to include CSS file in my project?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/erikflowers/weather-icons/issues/167>, or mute the
thread

**Comment by sailorsenergy** [comment]
I'd like to know the answer to this question too. This project is listed on the [Meteor package manager](https://atmospherejs.com/)  but there is no additional info about how to make the wind icons work. The only thing on the README that it says about the wind icons is:
> You must include the additional stylesheeet, weather-icons-wind.css to use the wind icons and API mappings.

It's not at all clear what that is referring to (e.g. SASS, LESS, etc...) or where you can find the `weather-icons-wind.css`. Please give us a little more info if you can.

**Comment by erikflowers** [comment]
It is this: https://github.com/erikflowers/weather-icons/blob/master/css/weather-icons-wind.css

As it is right now, a lot of people don't want to have the 360 degree classes and just rely on the cardinal directions, but this sheet is included for those who want 1 degree increments.

**Comment by sailorsenergy** [comment]
Thanks, @erikflowers ! I was able to get the wind icons working by just including that CSS in my Meteor project.

**Comment by kpagcha** [comment]
@sailorsenergy I don't know what a Meteor project is, but how did you manage to use the wind direction icons on Android?

**Comment by sailorsenergy** [comment]
@erikflowers I didn't say that I got it working on Android, just [Meteor](http://meteor.com/).

**Comment by kpagcha** [comment]
@sailorsenergy Oh okay my bad.
