### ISSUE TITLE
Not allowing me to install

### ISSUE THREAD

**Issue by Akshit1025** [erikflowers/weather-icons#244]
When I am installing it with node to create my weather app it is showing an error of an ssh key

**Please help !!!**

The error which is coming is :

```
npm ERR! command failed 
npm ERR! command git ls-remote ssh://git@github.com/erikflowers/weather-icons.git 
npm ERR! Permission denied (publickey). 
npm ERR! fatal: Could not read from remote repository.
npm ERR! Please make sure you have the correct access rights 
npm ERR! and the repository exists.
```

**Comment by fox91** [comment]
Hi @Akshit1025,
issue in this platform are intended to track issue, not to offer support.
I can advise you to use the download button (`.tar.gz` or `.zip`) and download the data in this way.

If, on the other hand, you believe that there is a problem with the repository or with the installation instructions, I ask you for more details on the operations you are performing (comendi, versions, etc.) in order to be able to identify the problem more easily.

**Comment by Akshit1025** [comment]
I am making a weather app with react js so I found your repo for the icons so I was installing it by typing 
`npm i  https://github.com/erikflowers/weather-icons.git` and it is giving me the above error.

**Please Help !!!!**

**Comment by fox91** [comment]
I tried it on a clean system (Debian `stretch`, node `v14.16.1`, npm `6.14.12`, git `2.11.0`) and it worked fine:
```
$ npm i https://github.com/erikflowers/weather-icons.git
+ weather-icons@2.0.12
added 1 package and audited 1 package in 8.543s
found 0 vulnerabilities
```
