### ISSUE TITLE
Anyone have the "wi-strong-wind" in a OTF / TTF file?

### ISSUE THREAD

**Issue by brohiem** [erikflowers/weather-icons#54]
I need to use this icon in photoshop but its not part of the OTF / TTF files in this repository.

![screen shot 2015-01-29 at 10 59 20 am](https://cloud.githubusercontent.com/assets/999907/5964067/08584d64-a7a6-11e4-9949-34fc7907a3d3.png)

**Comment by erik-intuit** [comment]
I am not sure what the problem is, the www.weathericons.io demo page has it and it shows up there, and it uses all the same files and fonts as the repo. 

I do see it in the Illustrator glyphs panel, which sucks because it doesn't show every glyph. And the cheatsheet hasn't been updated in a while (working on that). Were you trying to copy and paste it from the cheat sheet?

**Comment by brohiem** [comment]
Just trying to copy it from the font book on Mac.

**Comment by erikflowers** [comment]
There will be a better cheatsheet where the icons are directly selectable and copy/paste able. 2.0 is due out this week and will include that.
