### ISSUE TITLE
Missing period on classnames deg when using bower

### ISSUE THREAD

**Issue by LasseHaslev** [erikflowers/weather-icons#59]
I don't know why this is, but when i install using bower it seems like i get an older version, where the period is missing on the class names, where you are setting the degrees for the wind.

**Comment by erikflowers** [comment]
I will see if I can fix this. I don’t actually know how Bower works, it was something requested and added by someone else, so I think it has something to do with the version tag that it points to.

**Comment by skepsys** [comment]
If version is not marked directly, Bower tries to download the latest release, which currently is v1.3.2 from 1st of December, 2014. Fix for the bug with wind direction have been commited in master branch on 22nd of December, so it is not yet in the latest release.

@erikflowers, from your side the issue could be fixed just with making a new release from the current state of the master branch. Untill then, as a workaround, one can tell bower to use the master branch instead of a release (bower install weather-icons#master)

**Comment by r0b-** [comment]
+1

**Comment by erikflowers** [comment]
version 2.0 is due out this week and has new ways to do wind, and this should all be resolved.
