### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by abdelouahabb** [erikflowers/weather-icons#64]
sorry for this dumb question, but if i want to add an icon, and github doesent offer me the way to modify the main file because it is not text, how do I do ?

I added some icons (two from DejaVu) and separated some icons so I can animate them separately:
https://github.com/abdelouahabb/weather-fonts/blob/master/codes.png

**Comment by stenmuchow** [comment]
Fork, clone, change, commit, push, pull request. 
On Mar 14, 2015 9:53 PM, ALIANE Abdelouahab <notifications@github.com> wrote:sorry for this dumb question, but if i want to add an icon, and github doesent offer me the way to modify the main file because it is not text, how do I do ?

**Comment by abdelouahabb** [comment]
Yes,  but I have never worked with binaries on github

**Comment by morenoh149** [comment]
@abdelouahabb so assuming you have tools to modify font filetypes. You make your changes and add them with git.

**Comment by abdelouahabb** [comment]
I uploaded them to my repo, so in case someone is interrested to merge them ^_^
Thank you again for the wonderful work, I use them here: http://meteo-algeria.rhcloud.com/

**Comment by morenoh149** [comment]
@abdelouahabb submit a PR

**Comment by erikflowers** [comment]
With regards to adding actual icon artwork, the actual art itself, that would have to be maybe added as a new issue with a vector file attached. The master Glyphs.app file that the icon is built in is a binary and has a ton of metadata in the format etc. All new icons would have to be added by me to that file, then exported to the 4 webfont types, and then added to the less/sass.

This isn't hard to do if the artwork is provided, but as of right now where I must keep my Glyphs.app file as the single source of art, there's no way for someone to add to it since it's not text and can't be merged etc.

if you have new art you want, make an issue and attach the vector file, or a hi res png.
