### ISSUE TITLE
Outdated bower-package

### ISSUE THREAD

**Issue by flash1293** [erikflowers/weather-icons#80]
Hi, thank you for this awesome icons.

If I pull the icons via bower, the "main"-files in the bower.json file are wrong ("/dist/font" instead of "/font"), but here in the repository, they seem fine. Could you please update the bower-package with the correct main-files? I tried adding this repo directly as bower-dependency ("weather-icons": "git@github.com:erikflowers/weather-icons.git"), but it still pulls the old version.

Thanks in advance!

**Comment by erikflowers** [comment]
Supporting Bower here is something I really have no idea how it works, I rarely use CLI tools to install things, and have no firsthand knowledge of how to keep it configured properly with the repository. And honestly, I don't even know *how* it technically works with the tags/versions/branches etc. Someone else added it and I thought it would be helpful, but it causes more problems for me than it solves.

So I would love to update the bower package with the main files, but I don't know what that entails. If you or someone knows what to do and wants to make a pull request, I can look at that. Last time I did this, I had to update bower and then the repo a few times since I'd do one, and not the other, and break the whole thing.

I'm not a programmer at all, I have no idea what I'm doing =)

**Comment by erikflowers** [comment]
I changed the bower file to "font"

But it points to tag 1.3.2, which is a previous commit. Do I need to do it all over again and point it all to 1.3.3 and add a 1.3.3 tag?

**Comment by flash1293** [comment]
Hey, um yes, you would have to, but it is not that important, i can work around the problem. Thanks for your time :)

**Comment by erikflowers** [comment]
The bower file is updated, I just don’t know what will happen when someone tries to pull it down now.

**Comment by erikflowers** [comment]
I am going to be updating to a whole new 2.0 version this week so the bower file should be updated. But the odds that it is updated with errors are likely, since I don't really know how to do it =D
